######################################################################
# Automatically generated by qmake (3.0) Thu Oct 6 17:58:20 2016
######################################################################

TEMPLATE = app
QT += widgets
CONFIG += c++11
TARGET = app
INCLUDEPATH += .

# Input
HEADERS += src/Form.h
FORMS += src/dialog.ui
SOURCES += src/Form.cpp src/main.cpp
